# Generated by Django 4.0.4 on 2022-04-19 14:56

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_name', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(upload_to='BannerImages/%Y/%m/%d', verbose_name='image')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='CategoriesPicture/%Y/%m/%d', verbose_name='image')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(upload_to='Partners/%Y/%m/%d', verbose_name='image')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('header2', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(max_length=500)),
                ('short_description2', ckeditor_uploader.fields.RichTextUploadingField(max_length=2000)),
                ('full_description1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('full_description2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='InstrumentsImage/%Y/%m/%d', verbose_name='Picture for All View')),
                ('image2', models.ImageField(upload_to='InstrumentsImage/%Y/%m/%d', verbose_name='Picture 1 for Detail View')),
                ('image3', models.ImageField(upload_to='InstrumentsImage/%Y/%m/%d', verbose_name='Picture 2 for Detail View')),
                ('video', models.FileField(null=True, upload_to='InstrumentsVideos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('instrument_category', models.ManyToManyField(related_name='Category', to='Instruments.category', verbose_name='Main Category')),
            ],
        ),
    ]
