# Generated by Django 4.0.4 on 2022-04-22 17:34

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_name', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(upload_to='BannerImages/%Y/%m/%d', verbose_name='image')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='CategoriesPicture/%Y/%m/%d', verbose_name='image')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200, null=True, verbose_name='Header')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='Full description')),
                ('image', models.ImageField(upload_to='InstrumentsImage/%Y/%m/%d', verbose_name='Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ModelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200, null=True, verbose_name='Header')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='Full description')),
                ('image', models.ImageField(upload_to='ModelImage/%Y/%m/%d', verbose_name='Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(upload_to='Partners/%Y/%m/%d', verbose_name='image')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', ckeditor.fields.RichTextField(max_length=500, verbose_name='Short description')),
                ('video', models.FileField(null=True, upload_to='ModelsVideos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Video')),
                ('model_content', models.ManyToManyField(to='Instruments.modelcontent')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Instrument Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='InstrumentsImage/%Y/%m/%d')),
                ('short_description', ckeditor.fields.RichTextField(max_length=500, verbose_name='First Short description')),
                ('short_description2', ckeditor.fields.RichTextField(max_length=2000, verbose_name='Second Short description')),
                ('video', models.FileField(null=True, upload_to='InstrumentsVideos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Video')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument_Content', models.ManyToManyField(related_name='InstrumentContent', to='Instruments.instrumentcontent', verbose_name='InstrumentContent')),
                ('instrument_category', models.ManyToManyField(related_name='Category', to='Instruments.category', verbose_name='Main Category')),
                ('instrument_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Instrument_Model', to='Instruments.instrumentmodel', verbose_name='Instrument Model')),
            ],
        ),
    ]
