# Generated by Django 4.0.4 on 2022-04-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0002_instrumentmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='instrument_model',
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_model',
            field=models.ManyToManyField(related_name='Instrument_Model', to='Instruments.instrumentmodel', verbose_name='Instrument Model'),
        ),
    ]
