# Generated by Django 4.0 on 2021-12-29 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0002_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='staus',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 29, 20, 30, 52, 20455, tzinfo=utc)),
        ),
    ]
