# Generated by Django 4.0 on 2021-12-29 20:33

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0003_instruments_staus_alter_instruments_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='image')),
                ('stauts', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 29, 20, 33, 50, 672794, tzinfo=utc))),
                ('instrument_category', models.ManyToManyField(related_name='Category', to='Instruments.Category', verbose_name='Main Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Instruments',
        ),
    ]
