# Generated by Django 4.0.4 on 2022-04-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0003_remove_instrument_instrument_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentmodel',
            name='video',
        ),
        migrations.AddField(
            model_name='instrumentmodel',
            name='big_image',
            field=models.ImageField(default=0, upload_to='ModelImage/%Y/%m/%d', verbose_name='Header image '),
            preserve_default=False,
        ),
    ]
