# Generated by Django 4.0 on 2021-12-29 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0004_instrument_delete_instruments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='stauts',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
