# Generated by Django 4.0 on 2021-12-29 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0005_rename_stauts_instrument_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
