# Generated by Django 4.0 on 2021-12-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0006_alter_instrument_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(default=0, upload_to='image/%Y/%m/%d', verbose_name='image'),
            preserve_default=False,
        ),
    ]
