# Generated by Django 4.0 on 2022-01-04 19:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0007_alter_instrument_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True),
        ),
    ]
