# Generated by Django 4.0 on 2022-01-04 20:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0008_alter_instrument_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrument',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
