# Generated by Django 4.0 on 2022-01-04 20:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0009_alter_instrument_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200),
        ),
    ]
