# Generated by Django 4.0.1 on 2022-01-21 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0012_banneritems_category_status_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneritems',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
