# Generated by Django 4.0 on 2022-01-23 19:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0013_banneritems_date_category_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(upload_to='Partners/%Y/%m/%d', verbose_name='image')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
    ]
