# Generated by Django 4.0.4 on 2022-04-18 13:29

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0014_partner_alter_category_name_alter_instrument_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='full_description',
            new_name='full_description1',
        ),
        migrations.AddField(
            model_name='instrument',
            name='full_description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='image2',
            field=models.ImageField(default=0, upload_to='InstrumentsImage/%Y/%m/%d', verbose_name='Picture 1 for Detail View'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='image3',
            field=models.ImageField(default=0, upload_to='InstrumentsImage/%Y/%m/%d', verbose_name='Picture 2 for Detail View'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='video',
            field=models.FileField(null=True, upload_to='InstrumentsVideos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(upload_to='InstrumentsImage/%Y/%m/%d', verbose_name='Picture for All View'),
        ),
    ]
